version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres.afyhwaihedxliidkzclc:40026081@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
      - JWT_SECRET=dev_jwt_secret_key
      - JWT_EXPIRATION=1d
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
volumes:
  postgres_data:
