version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - USE_DYNAMODB=false
      - DB_DIALECT=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=jantungin
      - DB_USER=jantungin
      - DB_PASSWORD=jantungin_password
      - JWT_SECRET=dev_jwt_secret_key
      - JWT_EXPIRATION=1d
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=jantungin
      - MYSQL_USER=jantungin
      - MYSQL_PASSWORD=jantungin_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
